kind: Endpoints
apiVersion: v1
metadata:
  name: kube-scheduler-endpoint
  namespace: kube-system
  labels:
    k8s-app: kube-scheduler
subsets:
  - addresses:
      - ip: 172.17.8.100
    ports:
      - port: 10251